#!/bin/sh

if [ -f /etc/ttnovember/prestart ]; then
  /etc/ttnovember/prestart
fi

LAST_TIME_FILE=/etc/ttnovember/last_known_time
LAST_KNOWN_TIME="2018-02-16 14:06:11"

#if wget -q --spider --no-check-certificate https://www.astroprint.com; then
#  TMP_TIME_CHECK=/tmp/time_check
#  wget -q -O ${TMP_TIME_CHECK} --no-cache --no-check-certificate https://api.astroprint.com/time

#  #if the called failed, the file has zero bytes
#  if [ -s ${TMP_TIME_CHECK} ]; then
#    echo "`cat $TMP_TIME_CHECK`" > ${LAST_TIME_FILE}
#  fi
#
#  rm -f ${TMP_TIME_CHECK}
#fi
#
#if [ -f ${LAST_TIME_FILE} ]; then
#  LAST_KNOWN_TIME=`cat $LAST_TIME_FILE`
#fi

date -s "$LAST_KNOWN_TIME"
