#!/bin/sh
### BEGIN INIT INFO
# Provides:          ttnovember
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 3 4 5 6
# Short-Description: TTNovember
# Description:       Printer Controller Host
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
PIDFILE=/var/run/ttnovember.pid
ENABLED=1

if [ -e /etc/default/ttnovember ]; then
  . /etc/default/ttnovember
fi

test "$ENABLED" != "0" || exit 0

[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions

ttnovember_start()
{
  python -OO /ttnovember/run --config /etc/ttnovember/config.yaml --host 127.0.0.1 --daemon start --pid "$PIDFILE" || return 2
  return 0
}

ttnovember_stop()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return 0
  fi

  python -OO /ttnovember/run --daemon stop --config /etc/ttnovember/config.yaml --host 127.0.0.1 --pid "$PIDFILE" || return 2
}

ttnovember_restart()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return ttnovember_start
  fi

  python -OO /ttnovember/run --daemon restart --config /etc/ttnovember/config.yaml --host 127.0.0.1 --pid "$PIDFILE" || return 2
}

ttnovember_status()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return 3
  fi

  for pid in $(cat $PIDFILE) ; do
    if ! ps --no-headers p "$pid" | grep ttnovember > /dev/null ; then
      # program running, bogus pidfile
      return 1
    fi
  done

  return 0
}


case "$1" in
start)
  log_daemon_msg "Starting ttnovember" "ttnovember"

  if [ ! -f /etc/ttnovember/fs_expanded ]; then
    raspi-config --expand-rootfs
    echo "1" > /etc/ttnovember/fs_expanded
  fi

  if [ ! -f /etc/ttnovember/box-id ]; then
    if [ ! -f /etc/ttnovember/default-hostname ]; then
      log_daemon_msg "Setting initial hostname..." "ttnovember"
      python -OO /TTNovember/set-initial-hostname -c /etc/ttnovember/config.yaml

      log_daemon_msg "Executing first-time boot scripts" "ttnovember"

      if [ -d /etc/ttnovember/initial-scripts ]; then
        for f in /etc/ttnovember/initial-scripts/*
        do
          if [ -x "$f" ]; then
            log_daemon_msg "Executing $f..." "ttnovember"
            $f
          fi
        done
      fi

      log_daemon_msg "Rebooting..." "ttnovember"
      reboot
      exit 0
    fi
  fi

  MAX_NETWORK_RETRIES=10
  WAIT_BETWEEN_NETWORK_RETRIES=2
  PING_HOST=8.8.8.8
  NETWORK=0

  for i in `seq 1 $MAX_NETWORK_RETRIES`
  do
          if ping -W 2 -c 1 $PING_HOST > /dev/null 2>&1 ; then
                  NETWORK=1
                  break
          fi
          sleep $WAIT_BETWEEN_NETWORK_RETRIES
  done

  if [ $NETWORK = 0 ]; then
    service wifi_access_point start > /dev/null 2>&1
  fi

  /usr/local/sbin/ttnovember-init
  ttnovember_start
  ret=$?
  case "$ret" in
  0)
    log_end_msg 0
    ;;
  1)
    log_end_msg 1
    echo "pid file '$PIDFILE' found, ttnovember not started."
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  exit $ret
  ;;
stop)
  log_daemon_msg "Stopping ttnovember" "ttnovember"
  ttnovember_stop
  ret=$?
  case "$ret" in
  0|1)
    log_end_msg 0
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  exit $ret
  ;;
restart)
  log_daemon_msg "Restarting ttnovember" "ttnovember"
  ttnovember_restart
  case "$?" in
  0)
    log_end_msg 0
    ;;
  1)
    log_end_msg 1
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  ;;
status)
  ttnovember_status
  ret=$?
  case "$ret" in
  0)
    echo "ttnovember is running."
    ;;
  1)
    echo "ttnovember dead, but $PIDFILE exists."
    ;;
  *)
    echo "ttnovember not running."
    ;;
  esac
  exit $ret
  ;;
*)
  echo "Usage: /etc/init.d/ttnovember {start|stop|restart|status}"
  exit 2
  ;;
esac

:
